import Utils

public enum RuntimeEvents {
    public struct BlockImported: Event {
        public let block: BlockRef
        public let state: StateRef
        public let parentState: StateRef
    }

    public struct BlockFinalized: Event {
        public let hash: Data32
    }

    // New safrole ticket generated from SafroleService
    public struct SafroleTicketsGenerated: Event {
        public let epochIndex: EpochIndex
        public let items: [TicketItemAndOutput]
        public let publicKey: Bandersnatch.PublicKey
    }

    // New safrole ticket received from network
    public struct SafroleTicketsReceived: Event {
        public let items: [ExtrinsicTickets.TicketItem]

        public init(items: [ExtrinsicTickets.TicketItem]) {
            self.items = items
        }
    }

    // New block authored by BlockAuthor service
    public struct BlockAuthored: Event {
        public let block: BlockRef
    }

    // New WorkPackagesGenerated by Guaranteeing Service
    public struct WorkPackagesGenerated: Event {
        public let items: [WorkPackageAndOutput]
    }

    // WorkPackages Finalize by WorkPackages Service
    public struct WorkPackagesFinalized: Event {
        public let items: [WorkPackageAndOutput]
    }

    // New WorkReportGenerated by Guaranteeing Service
    public struct WorkReportGenerated: Event {
        public let items: [WorkReport]
    }

    // New GuaranteeGenerated by Guaranteeing Service
    public struct GuaranteeGenerated: Event {
        public let items: [WorkPackageAndOutput]
    }
}
