disabled_rules:
    - trailing_comma
    - todo
    - large_tuple
    - file_length
    - nesting
    - opening_brace
    - cyclomatic_complexity
    - blanket_disable_command
    - type_body_length
    - identifier_name
    - function_parameter_count
    - force_try
    - force_cast

excluded:
    - "**/.build"

type_name:
    min_length: 1

line_length:
    warning: 140
    error: 140
    ignores_function_declarations: true

function_body_length:
    warning: 200
    error: 500
