import Utils

extension Ref where T == ProtocolConfig {
    public static let dev = Ref(ProtocolConfig(
        auditTranchePeriod: 10,
        additionalMinBalancePerStateItem: 0,
        additionalMinBalancePerStateByte: 0,
        serviceMinBalance: 0,
        totalNumberOfCores: 1,
        preimagePurgePeriod: 10,
        epochLength: 10,
        auditBiasFactor: 10,
        coreAccumulationGas: 10,
        workPackageAuthorizerGas: 10,
        workPackageRefineGas: 10,
        recentHistorySize: 10,
        maxWorkItems: 10,
        maxTicketsPerExtrinsic: 10,
        maxLookupAnchorAge: 10,
        transferMemoSize: 10,
        ticketEntriesPerValidator: 10,
        maxAuthorizationsPoolItems: 10,
        slotPeriodSeconds: 10,
        maxAuthorizationsQueueItems: 10,
        coreAssignmentRotationPeriod: 10,
        maxServiceCodeSize: 10,
        preimageReplacementPeriod: 10,
        totalNumberOfValidators: 10,
        erasureCodedPieceSize: 10,
        maxWorkPackageManifestEntries: 10,
        maxEncodedWorkPackageSize: 10,
        maxEncodedWorkReportSize: 10,
        erasureCodedSegmentSize: 10,
        ticketSubmissionEndSlot: 10,
        pvmDynamicAddressAlignmentFactor: 10,
        pvmProgramInitInputDataSize: 10,
        pvmProgramInitPageSize: 10,
        pvmProgramInitSegmentSize: 10
    ))

    public static let prod = Ref(ProtocolConfig(
        auditTranchePeriod: 10,
        additionalMinBalancePerStateItem: 0,
        additionalMinBalancePerStateByte: 0,
        serviceMinBalance: 0,
        totalNumberOfCores: 1,
        preimagePurgePeriod: 10,
        epochLength: 10,
        auditBiasFactor: 10,
        coreAccumulationGas: 10,
        workPackageAuthorizerGas: 10,
        workPackageRefineGas: 10,
        recentHistorySize: 10,
        maxWorkItems: 10,
        maxTicketsPerExtrinsic: 10,
        maxLookupAnchorAge: 10,
        transferMemoSize: 10,
        ticketEntriesPerValidator: 10,
        maxAuthorizationsPoolItems: 10,
        slotPeriodSeconds: 10,
        maxAuthorizationsQueueItems: 10,
        coreAssignmentRotationPeriod: 10,
        maxServiceCodeSize: 10,
        preimageReplacementPeriod: 10,
        totalNumberOfValidators: 10,
        erasureCodedPieceSize: 10,
        maxWorkPackageManifestEntries: 10,
        maxEncodedWorkPackageSize: 10,
        maxEncodedWorkReportSize: 10,
        erasureCodedSegmentSize: 10,
        ticketSubmissionEndSlot: 10,
        pvmDynamicAddressAlignmentFactor: 10,
        pvmProgramInitInputDataSize: 10,
        pvmProgramInitPageSize: 10,
        pvmProgramInitSegmentSize: 10
    ))
}
