// generated by polka.codes
// JIT Exit Codes
//
// This file provides Swift enum values that match the C++ JIT exit codes.

import Foundation

/// Exit codes returned by the JIT-compiled code
enum JITExitCode: Int32 {
    case halt = 0
    case outOfGas = 1
    case fallback = 2 // Deprecated
    case pageFault = 3
    case trap = -1
    // Host call errors (high bits set)
    // These match JITHostCallError values when cast to Int32
    case hostRequestedHalt = -6      // 0xFFFFFFFA
    case hostPageFault = -5          // 0xFFFFFFFB
    case gasExhausted = -4           // 0xFFFFFFFC
    case hostFunctionThrewError = -3 // 0xFFFFFFFD
    case hostFunctionNotFound = -2   // 0xFFFFFFFE
    // Note: internalError (0xFFFFFFFF) collides with trap (-1)
}
