// generated by polka.codes
// This file defines the custom error types for the JIT compilation and execution process.

import Foundation

public enum JITError: Error, Equatable {
    case compilationFailed(details: String?)
    case memorySetupFailed(reason: String)
    case executionError(details: String?)
    case invalidReturnCode(code: Int32)
    case targetArchUnsupported(arch: String)
    case internalError(details: String)
    case invalidArgument(description: String)
    case memoryAllocationFailed(size: UInt32, context: String? = nil)
    case memoryCopyFailed(reason: String)
    case jitDisabled
    case vmInitializationError(details: String)
    case functionPointerNil
    case failedToGetBlobBaseAddress
    case failedToGetFlatMemoryBaseAddress
    case flatMemoryBufferSizeMismatch(expected: Int, actual: Int)
    case cppHelperError(code: Int32, details: String? = nil)
    case initializationError(details: String)
    case unsupportedArchitecture(host: String)
}
