[package]
name = "ec"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[build-dependencies]
cbindgen = "0.24.0"

[dependencies]
erasure-coding = { git = "https://github.com/paritytech/erasure-coding", branch = "main" }
