// generated by polka.codes
// Bridge between Swift and C++ for JIT compilation using AsmJit on AArch64 and x86_64

#ifndef HELPER_HH
#define HELPER_HH

#include <cstddef>
#include <cstdint>

// Function signature matching JITHostFunctionFnSwift in ExecutorBackendJIT.swift
// Returns: 0xFFFFFFFF on error, otherwise host call result
typedef uint32_t (* _Nonnull JITHostFunctionFn)(
	void* _Nonnull ownerContext,
	uint32_t hostCallIndex,
	uint64_t* _Nonnull guestRegisters,
	uint8_t* _Nonnull guestMemoryBase,
	uint32_t guestMemorySize,
	uint64_t* _Nonnull guestGas
);

// Table passed as `invocationContext` to JIT-compiled functions
struct JITHostFunctionTable {
    JITHostFunctionFn dispatchHostCall;
    void* _Nonnull ownerContext; // Opaque pointer to Swift ExecutorBackendJIT
};

// Trampoline for JIT code to call Swift host functions
// Returns: 0xFFFFFFFF on error, otherwise host call result (stored in PVM_R0)
uint32_t pvm_host_call_trampoline(
    JITHostFunctionTable* _Nonnull host_table,
    uint32_t host_call_index,
    uint64_t* _Nonnull guest_registers_ptr,
    uint8_t* _Nonnull guest_memory_base_ptr,
    uint32_t guest_memory_size,
    uint64_t* _Nonnull guest_gas_ptr);

#endif // HELPER_HH
