[package]
name = "bls"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[build-dependencies]
cbindgen = "0.27.0"

[dependencies]
w3f-bls = { git = "https://github.com/w3f/bls", rev = "c19bbe8", features = [
	"experimental",
] }

[dev-dependencies]
hex-literal = "0.4.1"
