// generated by polka.codes
// This file defines the protocol for platform-specific JIT operations.

import Foundation
import Utils // For PvmConfig

// TODO: Ensure PvmConfig is accessible here. It might require an import from the main PolkaVM module.

/// A protocol defining methods for platform-specific JIT (Just-In-Time) compilation operations.
/// Implementations of this protocol will provide concrete strategies for different operating systems
/// and architectures, such as determining the target architecture for compilation.
protocol JITPlatformStrategy {
    /// Determines the target architecture string for JIT compilation.
    ///
    /// This method considers any architecture specified in the `PvmConfig` first.
    /// If no architecture is specified or if "native" is specified, it attempts to
    /// auto-detect the host machine's architecture.
    ///
    /// - Parameter config: The `PvmConfig` instance which may contain a user-specified
    ///   target architecture.
    /// - Returns: A string representing the target architecture (e.g., "aarch64-apple-darwin",
    ///   "x86_64-unknown-linux-gnu").
    /// - Throws: `JITError.targetArchUnsupported` if the architecture cannot be determined
    ///   or is not supported.
    func getCurrentTargetArchitecture(config: PvmConfig) throws -> String
}
